### ISSUE TITLE
Adding fill text on the main part ("above the fold")

### ISSUE THREAD

**Issue by Ryuno-Ki** [Mte90/MozStrap#3]
Look at https://github.com/mozilla/Community-Design/issues/3#issuecomment-204541159 for the original comment.

It would be handy to have some information about this project in the right of the navigation (where Navbar, Buttons, Typography etc. are listed).

Otherwise it looks empty. I wasn't aware of the fact that I had to scroll down to see further information.

**Comment by Mte90** [comment]
This is for https://github.com/Mte90/WP-Mozilla
