### ISSUE TITLE
Switching Themes yield 404s

### ISSUE THREAD

**Issue by Ryuno-Ki** [Mte90/MozStrap#4]
Look at https://github.com/mozilla/Community-Design/issues/3#issuecomment-204541159 for the original comment.

When choosing a theme from the dropdown in the top navbar, I get a 404. Either intercept the click with JavaScript or add content in https://mte90.github.io/cosmo/ https://mte90.github.io/paper/ and so on …

**Comment by Mte90** [comment]
Dropdown?

**Comment by Ryuno-Ki** [comment]
![mozstrap-dropdown](https://cloud.githubusercontent.com/assets/3097194/14441449/1abdac22-0035-11e6-9d26-d188a048effa.png)

Dropdown.

**Comment by Mte90** [comment]
So this is a bug of the demo, is easy to fix.
