### ISSUE TITLE
Language switcher opens in a new tab

### ISSUE THREAD

**Issue by Ryuno-Ki** [Mte90/MozStrap#7]
Look at https://github.com/mozilla/Community-Design/issues/3#issuecomment-204541159 for the original comment.

When clicking on "EN" or "IT" in the upper right, a new tab gets opened.
If that isn't on purpose, please remove `target="_blank"` from the `<a>`.

**Comment by Mte90** [comment]
This is for https://github.com/Mte90/WP-Mozilla
