### ISSUE TITLE
Make validators happy

### ISSUE THREAD

**Issue by Ryuno-Ki** [Mte90/MozStrap#8]
Look at https://github.com/mozilla/Community-Design/issues/3#issuecomment-204541159 for the original comment.
- [ ] https://validator.w3.org/nu/?doc=https%3A%2F%2Fmte90.github.io%2FMozStrap%2F (great!)
- [ ] https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fmte90.github.io%2FMozStrap%2F&profile=css3&usermedium=all&warning=1 (Bootstrap always fails the validation there)
- [ ] https://tenon.io/testNow.php?url=https://mte90.github.io/MozStrap/
- [ ] https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fmte90.github.io%2FMozStrap%2F (fine!)

**Comment by Mte90** [comment]
Some the point are for https://github.com/Mte90/WP-Mozilla

**Comment by Ryuno-Ki** [comment]
You should really have linked that repo in the comment at Community-Design.

Sorry for filling against the wrong repo. I picked the nearest link you provided.

**Comment by Mte90** [comment]
No worry :-)
